name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on: 
  push:
    branches:
      - master
  pull_request:
    branches:  
      - master

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/clouduserpa9ea2ef4/Java-Project
            azure-pipeline-name: 'Java-Project'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
